export {default as About} from './About'
export {default as Home} from './Home'
export {default as ListAll} from './ListAll'
export {default as Random} from './Random'
export {default as Navbar} from './Navbar'